<a href="https://colab.research.google.com/github/Samuelcb08/Actividades_Nuevastecnologias/blob/main/alquileres_vivienda.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
datos_viviendas = pd.read_csv("/content/drive/MyDrive/Alquileres_viviendas.csv", sep = ";")

In [ ]:
datos_viviendas.head(65)

,Unnamed: 0,Tipo,Distrito,Cuartos,Vacantes,Suites,Area,Valor,Mantenimiento,Impuesto
0,0,Casa,Lurigancho,2,0,1,100,7000.0,NaN,NaN
1,1,Departamento,Pachacámac,1,0,0,15,800.0,390.0,20.0
2,2,Departamento,Ate,1,0,0,48,800.0,230.0,NaN
3,3,Departamento,Barranco,3,1,0,70,1200.0,NaN,NaN
4,4,Departamento,Comas,2,0,0,50,1300.0,301.0,17.0
...,...,...,...,...,...,...,...,...,...,...
60,60,Departamento,San Juan de Lurigancho,3,4,0,130,5500.0,1407.0,246.0
61,61,Departamento,Chaclacayo,2,1,0,77,1500.0,740.0,NaN
62,62,Departamento,Ate,3,2,2,85,2500.0,1400.0,190.0
63,63,Departamento,Santa Anita,3,1,1,78,1450.0,630.0,73.0
64,64,Departamento,Punta Hermosa,2,1,0,54,2300.0,582.0,NaN

In [ ]:
sel_departamentos = datos_viviendas["Tipo"]== "Departamento"
cant_dpto_otras = datos_viviendas[~sel_departamentos].shape[0]
cant_dpto_otras

967

In [ ]:
sel_casa_hab_cochera = (datos_viviendas["Tipo"] == "Casa") | (datos_viviendas["Tipo"] == "Departamento" ) | (datos_viviendas["Tipo"] == "Cochera")
cant_casa_hab_cochera = datos_viviendas[sel_casa_hab_cochera].shape[0]
cant_casa_hab_cochera

20499

In [ ]:
sel_area = (datos_viviendas['Area']>=60)& (datos_viviendas['Area']<=100)
sel_area
cantidad_viv_area = datos_viviendas[sel_area].shape[0]
cantidad_viv_area

8510

In [ ]:
sel_hab_precio = (datos_viviendas['Cuartos']>=4) &(datos_viviendas['Valor']<= 2000)
cant_hab_precio = datos_viviendas[sel_hab_precio].shape[0]
cant_hab_precio

55

In [ ]:
print("Se encontraron los siguientes resultados: ")
print(f"El numero de departamentos es de {cant_dpto}")
print(f"el numero de viviendas restantes es de {cant_dpto_otras}")
print(f"El numero de viviendas de tipo casa, departamento es {cant_casa_hab_cochera}")
print(f"la cantidad con un area entre 60 y 100 metros cuadrados es de {cantidad_viv_area}")

Se encontraron los siguientes resultados:
El numero de departamentos es de 967
el numero de viviendas restantes es de 967
El numero de viviendas de tipo casa, departamento es 20499
la cantidad con un area entre 60 y 100 metros cuadrados es de8510

In [ ]:
datos_viviendas.info

<bound method DataFrame.info of        Unnamed: 0          Tipo     Distrito  Cuartos  Vacantes  Suites  Area  \
0               0          Casa   Lurigancho        2         0       1   100
1               1  Departamento   Pachacámac        1         0       0    15
2               2  Departamento          Ate        1         0       0    48
3               3  Departamento     Barranco        3         1       0    70
4               4  Departamento        Comas        2         0       0    50
...           ...           ...          ...      ...       ...     ...   ...
20494       20494  Departamento          Ate        2         0       0    52
20495       20495  Departamento  Santa Anita        2         0       0    70
20496       20496  Departamento        Lince        3         1       2    78
20497       20497  Departamento        Rímac        2         1       0    48
20498       20498  Departamento        Rímac        2         0       0    70

        Valor  Mantenimiento  Impuesto
0      7000.0            NaN       NaN
1       800.0          390.0      20.0
2       800.0          230.0       NaN
3      1200.0            NaN       NaN
4      1300.0          301.0      17.0
...       ...            ...       ...
20494  1000.0          550.0       NaN
20495   900.0          490.0      48.0
20496  1800.0          800.0      40.0
20497  1400.0          509.0      37.0
20498  3000.0          760.0       NaN

[20499 rows x 10 columns]>

In [ ]:
datos_viviendas[datos_viviendas['Valor'].isnull()]

,Unnamed: 0,Tipo,Distrito,Cuartos,Vacantes,Suites,Area,Valor,Mantenimiento,Impuesto
50,50,Departamento,Ate,2,1,1,70,NaN,970.0,68.0
1355,1355,Departamento,San Bartolo,2,0,0,75,NaN,878.0,NaN
1529,1529,Casa,Lince,3,4,3,363,NaN,NaN,NaN
1831,1831,Departamento,Chorrillos,2,0,0,95,NaN,1010.0,170.0
1853,1853,Departamento,San Borja,2,0,0,72,NaN,850.0,NaN
4498,4498,Casa,Lince,3,2,1,100,NaN,NaN,NaN
7794,7794,Departamento,San Bartolo,2,0,1,75,NaN,878.0,NaN
8146,8146,Departamento,La Punta,3,0,1,135,NaN,910.0,228.0
8326,8326,Departamento,La Perla,3,1,1,105,NaN,880.0,221.0

In [ ]:
viviendas_nan = datos_viviendas.shape[0]
datos_viviendas.dropna(subset= ['Valor'],inplace= True)
viviendas_nan_b = datos_viviendas.shape[0]
viviendas_nan - viviendas_nan_b

9

In [ ]:
datos_viviendas[datos_viviendas['Valor'].isnull()]

Empty DataFrame
Columns: [Unnamed: 0, Tipo, Distrito, Cuartos, Vacantes, Suites, Area, Valor, Mantenimiento, Impuesto]
Index: []

In [ ]:
datos_viviendas[datos_viviendas['Mantenimiento'].isnull()].shape[0]

1500

In [ ]:
sel= (datos_viviendas['Tipo'] == 'Departamento')&(datos_viviendas['Mantenimiento'].isnull())

In [ ]:
sel_A = datos_viviendas.shape[0]
datos_viviendas = datos_viviendas[~sel]
sel_B = datos_viviendas[0]
sel_A - sel_B

KeyError: ignored

In [ ]:
sel.shape[0]

19745

NameError: ignored